Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('AED','UAE Dirham',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('AFN','Afghani',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ALL','Lek',null,'L');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('AMD','Armenian Dram',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('AOA','Kwanza',null,'Kz');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ARS','Argentine Peso',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('AUD','Australian Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('AZN','Azerbaijani Manat',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BAM','Convertible Mark',null,'??');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BBD','Barbados Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BDT','Taka',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BGN','Bulgarian Lev',null,'??');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BHD','Bahraini Dinar',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BIF','Burundi Franc',null,'FBu');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BND','Brunei Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BOB','Boliviano',null,'Bs.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BRL','Brazilian Real',null,'R$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BSD','Bahamian Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BTN','Ngultrum',null,'Nu.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BWP','Pula',null,'P');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BYN','Belarusian Ruble',null,'Br');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('BZD','Belize Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CAD','Canadian Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CDF','Congolese Franc',null,'FC');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CHF','Swiss Franc',null,'CHF');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CLP','Chilean Peso',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CNY','Yuan Renminbi',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('COP','Colombian Peso',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CRC','Costa Rican Colon','Costa Rican Col?n','?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CUC','Peso Convertible',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CUP','Cuban Peso',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CVE','Cabo Verde Escudo',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('CZK','Czech Koruna',null,'K?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('DJF','Djibouti Franc',null,'Fdj');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('DKK','Danish Krone',null,'kr.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('DOP','Dominican Peso',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('DZD','Algerian Dinar',null,'??');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('EGP','Egyptian Pound',null,'E?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ERN','Nakfa',null,'Nkf');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ETB','Ethiopian Birr',null,'Br');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('EUR','Euro',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('FJD','Fiji Dollar',null,'FJ$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GBP','Pound Sterling',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GEL','Lari',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GHS','Ghana Cedi',null,'GH?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GMD','Dalasi',null,'D');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GNF','Guinea Franc',null,'FG');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GTQ','Quetzal',null,'Q');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('GYD','Guyana Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('HNL','Lempira',null,'L');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('HRK','Kuna',null,'kn');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('HTG','Gourde',null,'G');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('HUF','Forint',null,'Ft');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('IDR','Rupiah',null,'Rp');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ILS','New Israeli Sheqel',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('INR','Indian Rupee',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('IQD','Iraqi Dinar',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('IRR','Iranian Rial',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ISK','Iceland Krona',null,'kr');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('JMD','Jamaican Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('JOD','Jordanian Dinar',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('JPY','Yen',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KES','Kenyan Shilling',null,'KSh');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KGS','Som',null,'???');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KHR','Riel',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KMF','Comoro Franc',null,'CF');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KPW','North Korean Won',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KRW','Won',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KWD','Kuwaiti Dinar',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('KZT','Tenge',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('LAK','Lao Kip',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('LBP','Lebanese Pound',null,'?.?.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('LKR','Sri Lanka Rupee',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('LRD','Liberian Dollar',null,'L$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('LSL','Loti',null,'L');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('LYD','Libyan Dinar',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MAD','Moroccan Dirham',null,'DH');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MDL','Moldovan Leu',null,'L');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MGA','Malagasy Ariary',null,'Ar');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MKD','Denar',null,'den');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MMK','Kyat',null,'K');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MNT','Tugrik',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MRU','Ouguiya',null,'UM');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MUR','Mauritius Rupee',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MVR','Rufiyaa',null,'Rf');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MWK','Malawian Kwacha',null,'K');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MXN','Mexican Peso',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MYR','Malaysian Ringgit',null,'RM');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('MZN','Mozambique Metical',null,'MT');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('NAD','Namibian Dollar',null,'N$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('NGN','Naira',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('NIO','Cordoba Oro','C?rdoba Oro','C$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('NOK','Norwegian Krone',null,'kr');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('NPR','Nepalese Rupee',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('NZD','New Zealand Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('OMR','Rial Omani',null,'?.?.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('PEN','Sol',null,'S/');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('PGK','Kina',null,'K');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('PHP','Philippine Peso',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('PKR','Pakistan Rupee',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('PLN','Zloty','Z?oty','z?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('PYG','Guarani','Guaran?','?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('QAR','Qatari Rial',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('RON','Romanian Leu',null,'L');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('RSD','Serbian Dinar',null,'???');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('RUB','Russian Ruble',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('RWF','Rwanda Franc',null,'FRw');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SAR','Saudi Riyal',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SBD','Solomon Islands Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SCR','Seychelles Rupee',null,'SRe');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SDG','Sudanese Pound',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SEK','Swedish Krona',null,'kr');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SGD','Singapore Dollar',null,'S$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SLL','Leone',null,'Le');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SOS','Somali Shilling',null,'Sh.So.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SRD','Surinam Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SSP','South Sudanese Pound',null,'SS?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('STN','Dobra',null,'Db');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SVC','El Salvador Colon','El Salvador Col?n','?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SYP','Syrian Pound',null,'LS');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('SZL','Lilangeni',null,'L');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('THB','Baht',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TJS','Somoni',null,'SM');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TMT','Turkmenistan New Manat',null,'T');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TND','Tunisian Dinar',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TOP','Pa''anga','Pa?anga','T$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TRY','Turkish Lira',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TTD','Trinidad and Tobago Dollar',null,'TT$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TWD','New Taiwan Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('TZS','Tanzanian Shilling',null,'TSh');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('UAH','Hryvnia',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('UGX','Uganda Shilling',null,'USh');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('USD','United States Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('UYU','Peso Uruguayo',null,'$U');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('UZS','Uzbekistan Sum',null,'??');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('VES','Bolivar Soberano','Bol?var Soberano','Bs.S.');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('VND','Dong',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('VUV','Vatu',null,'VT');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('WST','Samoan Tala',null,'WS$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('XAF','Central African CFA Franc',null,'?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('XCD','East Caribbean Dollar',null,'$');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('XOF','West African CFA Franc',null,'CFA');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('YER','Yemeni Rial',null,'?.?');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ZAR','Rand',null,'R');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ZMW','Zambian Kwacha',null,'K');
Insert into CURRENCIES (CURRENCY_ID,NAME,OFFICIAL_NAME,SYMBOL) values ('ZWL','Zimbabwe Dollar',null,'$');
